ParkingClub/config/routes.rb
ParkingClub::Application.routes.draw do
  root "welcome#index"

  resources :users do
    collection do
      get :new_owner
    end
  end

  resources :lots do
    resources :memberships
  end

  resources :sessions, only: [:new, :create, :destroy]

  delete "logout" => "sessions#destroy", as: "logout"

  get "login" => "sessions#new", as: "login"


end

ParkingClub/app/models/lot.rb
class Lot < ActiveRecord::Base

  belongs_to :owner, class_name: "User", :foreign_key => "owner_id"

  has_many :memberships

  has_many :users, through: :memberships

  geocoded_by :lot_address

  acts_as_gmappable

  reverse_geocoded_by :latitude, :longitude, :lot_address => :full_address
  validates :name, :address, :city, :province, :country, :daily_rate_in_cents, presence: true

  after_validation :geocode, :reverse_geocode

  def lot_address
    [address, city, province, country].compact.join(', ')
  end

  def search_address
    [address, city, province, country].compact.join(', ')
  end

  def self.search(search)
    if search
      @lots = Lot.near(search, 5, :units => :km)
    else
      @lots = Lot.all
    end
  end

end

ParkingClub/app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :lot
  belongs_to :user

  validates :start_time, :end_time, presence: true

  def days_remaining
  self.end_time - Time.now
  end

end

ParkingClub/app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :lots, through: :memberships
  has_many :memberships

  has_many :owned_lots, :class_name => 'Lot', :foreign_key => 'owner_id'

  validates :first_name, :last_name, :email, :password, presence: true
  validates :owner, :inclusion => { :in => [true, false] }
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password

end

ParkingClub/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ParkingClub/app/controllers/lots_controller.rb
class LotsController < ApplicationController

  before_action :require_login

  def index
    @lots = Lot.search(params[:search])
    @json = Lot.search(params[:search]).to_gmaps4rails
  end

  def new
    if current_user.owner
      @lot = current_user.owned_lots.build
    end
  end

  def create
    if current_user.owner
    @lot = current_user.owned_lots.build(lot_params)
      if @lot.save
        redirect_to lot_path(@lot), notice: "Project created!"
      else
        render :new
      end
    end
  end

  def show
    @lot = Lot.find(params[:id])
    @membership = @lot.memberships.build
  end

  protected

  def lot_params
    params.require(:lot).permit(:name, :country, :province, :city, :latitude, :longitude, :address, :owner_id, :daily_rate_in_cents)
  end


end

ParkingClub/app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

  before_action :require_login
  before_action :require_lot, except: [:index]

  def index
    @memberships = Membership.find(params[:user_id])
  end

  def new
    @membership = @lot.memberships.build
  end

  def create
    @membership = @lot.memberships.build(membership_params)
    @membership.user_id = current_user.id
    if @membership.save
      redirect_to user_path(id: current_user.id)
    else
      redirect_to lot_path(@lot), notice: "Something went wrong"
    end
  end

  protected

  def membership_params 
    params.require(:membership).permit(:user_id, :lot_id, :start_time, :end_time)
  end

  def require_lot
    @lot = Lot.find(params[:lot_id])
  end

end

ParkingClub/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to root_path
    else
      flash.now[:alert] = "Invalid"; render :action => "new"
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

ParkingClub/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_login, except: [:new, :create, :new_owner]

  def new
    @user = User.new
  end

  def new_owner
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, notice: "Welcome, #{@user.first_name}!"
    else
      render :new, notice: "Something went wrong, try again"
    end
  end

  def show
    @user = User.find_by(params[:id])
    @memberships = current_user.memberships
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :owner, :password_confirmation)
  end

end

ParkingClub/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

ParkingClub/app/helpers/application_helper.rb
module ApplicationHelper
end

ParkingClub/app/helpers/lots_helper.rb
module LotsHelper
end

ParkingClub/app/helpers/memberships_helper.rb
module MembershipsHelper
end

ParkingClub/app/helpers/sessions_helper.rb
module SessionsHelper
end

ParkingClub/app/helpers/users_helper.rb
module UsersHelper
end

ParkingClub/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ParkingClub/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParkingClub</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield :scripts %>
  <%= stylesheet_link_tag 'gmaps4rails' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div>
<%= render 'layouts/shared/nav' %>
<%= render 'layouts/shared/side_search' %>
<%= render 'layouts/shared/show_flash' %>
<%= yield %>
<%= render 'layouts/shared/nav_footer' %>
</div>

</body>
</html>

ParkingClub/app/views/layouts/shared/_form_errors.html.erb
<% unless target.errors.empty? %>
    <div class="alert alert-error">
      <strong>Oops!</strong>
      <ul>
        <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <%end%>
      </ul>
    </div>
<%end%>

ParkingClub/app/views/layouts/shared/_nav.html.erb
<div class="navbar navbar-default navbar-inverse navbar-fixed-top navtop">
  <div class="navbar-inner navtop1">
    <div class="navcontainer">
      <img id="parkinglogo" src="/assets/parkingclub8.png">
      <div class="nav-collapse collapse navynav">
        <ul class="nav">
          <li class="divider-vertical"></li>
          <li class="active"><%= link_to "Home", root_path %></li>
        </ul>
        <div class="pull-right navnav">
          <% if logged_in? %>
            <%= link_to "#{current_user.first_name} #{current_user.last_name}", user_path(id: current_user.id), class: 'btn btn-default' %>
            <%= link_to 'Logout', logout_path, method: :delete, class: 'btn btn-default logout-btn' %>
          <% else %>
            <%= link_to 'Log In', login_path, class: 'btn btn-default login-btn' %>
            <%= link_to 'Sign Up', new_user_path, class: 'btn btn-default signup-btn' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

ParkingClub/app/views/layouts/shared/_nav_footer.html.erb
<!-- <div class="navbar-fixed-bottom navbar navbar-default navbar-inverse navfooter">
  <div class="nav-inner navfooter-inner">
    <div class="container navfooter-container">
      <div class="nav-collapse collapse navfooter-collapse">
        <div class="pull-right navfooter-pull-right">
          <%= link_to "Business Solutions", new_owner_users_path %>
        </div>
      </div>
    </div>
  </div>
</div>
 -->

ParkingClub/app/views/layouts/shared/_show_flash.html.erb
<% if flash[:notice] %>
  <div><%= flash[:notice] %></div>
<%end%>

<% if flash[:alert] %>
  <div><%= flash[:alert] %></div>
<%end%>

ParkingClub/app/views/layouts/shared/_side_search.html.erb
<div class="jumbotron hideside">
  <div class="container sidebar">
    <div class="lot-search">
      <%= form_tag lots_path, :method => 'get' do %>
        <%= text_field_tag :search, params[:search], :placeholder => "Enter a location", class: 'searchbar' %>
        <%= submit_tag "Search", :name => nil, class: 'btn btn-default login-btn search-side-button' %>
      <%end%>
    </div>
  </div>
</div>

ParkingClub/app/views/lots/_lot_form.html.erb
<%= f.text_field :name, :placeholder => "Name" %><br>

<%= f.text_field :address, :placeholder => "Address" %><br>

<%= f.text_field :city, :placeholder => "City" %><br>

<%= f.text_field :province, :placeholder => "Province" %><br>

<%= f.text_field :country, :placeholder => "Country" %><br>

<%= f.text_field :daily_rate_in_cents, :placeholder => "Daily Rate" %><br>
<hr />

<%= f.submit "Save", class: 'btn btn-default login-btn lot-btn' %>

<%= render 'layouts/shared/form_errors', target: f.object %>

ParkingClub/app/views/lots/index.html.erb
<%= gmaps( :map_options => { :container_class => "lot-map" }, "markers" => {"data" => @json, "options" => {"auto_zoom" => false} }) %>

<div class="result-wrapper">
  <% @lots.each do |lot| %>
    <div class="test-lot-search">
    <%= link_to lot.name, lot_path(lot) %>
    </div>
  <% end %>
</div>

ParkingClub/app/views/lots/new.html.erb
<div class="lot-form">
  <div class="lot-info">
  <%= form_for @lot do |f| %>
    <%= render 'lot_form', f: f %>
  <%end%>
  </div>
</div>

ParkingClub/app/views/lots/show.html.erb
<h1><%= @lot.name %></h1>

<div class="membership-form">
  <%= form_for [@lot, @membership] do |f| %>

    <%= f.label :start_time %>
    <%= f.datetime_select :start_time %>

    <%= f.label :end_time %>
    <%= f.datetime_select :end_time %>

    <%= f.submit %>

  <%end%>
</div>

<div class="pull-left map">
  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@lot.latitude}%2C#{@lot.longitude}" %>
</div>

ParkingClub/app/views/users/_form.html.erb
<%= f.text_field :first_name, :placeholder => "First Name" %><br>

<%= f.text_field :last_name, :placeholder => "Last Name" %><br>

<%= f.text_field :email, :placeholder => "Email" %><br>

<%= f.password_field :password, :placeholder => "Password" %><br>

<%= f.password_field :password_confirmation, :placeholder => "Confirm Password" %><br>

<%= f.submit class: 'btn btn-default submitbtn' %>

<!-- 'target' symbol is defined in '_form_errors' partial -->
<%= render '/layouts/shared/form_errors', target: f.object %> 

ParkingClub/app/views/users/new.html.erb
<div class="user-form" id="user">
  <div id="form">
  <%= form_for @user do |f| %>
    <%= render 'form', f: f %>
  <% end %>
  </div>
</div>

ParkingClub/app/views/users/new_owner.html.erb
<div class="user-form">
  <%= form_for @user do |f| %>

    <%= f.hidden_field :owner, :value => true %>

    <%= render 'form', f: f %>
  <% end %>
</div>

ParkingClub/app/views/users/show.html.erb
<h1 class="passes-header">My Passes</h1>


<% @memberships.each do |membership| %>
<div class="user-membership">

  <div>
    <p><%= membership.lot.name %></p>
    <p>Purchased On: <%= membership.created_at.strftime("%m/%d/%Y") %></p>
  </div>

  <div>
    <p><%= distance_of_time_in_words(membership.days_remaining)%> Remaining</p>
  </div>

</div>
<%end%>